# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: |
        npm install -g pkg-fetch
        pkg-fetch --platform linux --node-range node16
        pkg-fetch --platform mac --node-range node16
        pkg-fetch --platform win --node-range node16 
    - run: |
        yarn install --immutable --inline-builds
        yarn run release:all --verbose
    - name: Archive mac production artifacts
      uses: actions/upload-artifact@v3
      with: 
        name: mac
        path: release/mac
    - name: Archive linux production artifacts
      uses: actions/upload-artifact@v3
      with: 
        name: linux
        path: release/linux
    - name: Archive windows production artifacts
      uses: actions/upload-artifact@v3
      with: 
        name: windows
        path: release/win
